apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-service
  namespace: ${NAMESPACE}
  labels:
    lenschain.io/runtime-type: ctf-attack-defense
    lenschain.io/runtime-role: judge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: judge-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: judge-service
        lenschain.io/runtime-role: judge-service
    spec:
      containers:
        - name: judge-service
          image: ${JUDGE_SERVICE_IMAGE}
          imagePullPolicy: IfNotPresent
