apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-tools-${TEAM_ID}
  namespace: ${NAMESPACE}
  labels:
    lenschain.io/runtime-type: ctf-attack-defense
    lenschain.io/runtime-role: team-tools
    lenschain.io/team-id: ${TEAM_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: team-tools-${TEAM_ID}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: team-tools-${TEAM_ID}
        lenschain.io/runtime-role: team-tools
        lenschain.io/team-id: ${TEAM_ID}
    spec:
      containers:
        - name: team-tools
          image: ${TEAM_TOOLS_IMAGE}
          imagePullPolicy: IfNotPresent
