apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-runtime
  namespace: ${NAMESPACE}
  labels:
    lenschain.io/runtime-type: ctf-jeopardy
    lenschain.io/challenge-type: ${CHALLENGE_TYPE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: challenge-runtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: challenge-runtime
        lenschain.io/runtime-type: ctf-jeopardy
    spec:
      containers:
        - name: challenge-runtime
          image: ${CHALLENGE_IMAGE}
          imagePullPolicy: IfNotPresent
          env:
            - name: CTF_COMPETITION_ID
              value: "${COMPETITION_ID}"
            - name: CTF_TEAM_ID
              value: "${TEAM_ID}"
            - name: CTF_CHALLENGE_ID
              value: "${CHALLENGE_ID}"
            - name: CTF_FLAG_MODE
              value: "${FLAG_MODE}"
            - name: CTF_FLAG
              value: "${FLAG_VALUE}"
