apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-chain
  namespace: ${NAMESPACE}
  labels:
    lenschain.io/runtime-type: ctf-attack-defense
    lenschain.io/runtime-role: judge-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: judge-chain
  template:
    metadata:
      labels:
        app.kubernetes.io/name: judge-chain
        lenschain.io/runtime-role: judge-chain
    spec:
      containers:
        - name: judge-chain
          image: ${JUDGE_CHAIN_IMAGE}
          imagePullPolicy: IfNotPresent
