apiVersion: v1
kind: ResourceQuota
metadata:
  name: runtime-quota
  namespace: ${NAMESPACE}
  labels:
    lenschain.io/runtime-type: ${RUNTIME_TYPE}
    lenschain.io/runtime-scope: dynamic
spec:
  hard:
    requests.cpu: ${REQUESTS_CPU}
    requests.memory: ${REQUESTS_MEMORY}
    limits.cpu: ${LIMITS_CPU}
    limits.memory: ${LIMITS_MEMORY}
    requests.storage: ${REQUESTS_STORAGE}
    pods: "${MAX_PODS}"
