apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: lenschain
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: lenschain
    app.kubernetes.io/managed-by: kustomize
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: api
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: console
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: lenschain
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: lenschain
type: Opaque
stringData:
  root-user: minioadmin
  root-password: CHANGE_ME
