apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: lenschain-platform
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: lenschain

data:
  LENSCHAIN_SERVER_HOST: "0.0.0.0"
  LENSCHAIN_SERVER_PORT: "3000"
  LENSCHAIN_DATABASE_HOST: postgres
  LENSCHAIN_DATABASE_PORT: "5432"
  LENSCHAIN_DATABASE_DBNAME: lenschain
  LENSCHAIN_DATABASE_SSLMODE: disable
  LENSCHAIN_REDIS_HOST: redis
  LENSCHAIN_REDIS_PORT: "6379"
  LENSCHAIN_MINIO_ENDPOINT: minio:9000
  LENSCHAIN_MINIO_BUCKET: lenschain
  LENSCHAIN_MINIO_USE_SSL: "false"
  LENSCHAIN_NATS_URL: nats://nats:4222
  LENSCHAIN_SIM_ENGINE_GRPC_ADDR: sim-engine:9090
