apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: lenschain-platform
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/part-of: lenschain
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats
        app.kubernetes.io/part-of: lenschain
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          args: ["-js"]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
