apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: platform-default-policy
  namespace: lenschain-platform
  labels:
    app.kubernetes.io/part-of: lenschain
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
