apiVersion: v1
kind: Secret
metadata:
  name: platform-infra-secret
  namespace: lenschain-platform
  labels:
    app.kubernetes.io/name: platform-infra
    app.kubernetes.io/part-of: lenschain
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: change-me
