package catalog

import (
	"github.com/lenschain/sim-engine/scenarios/internal/attacksecurity/doublespend"
	"github.com/lenschain/sim-engine/scenarios/internal/attacksecurity/fiftyoneattack"
	"github.com/lenschain/sim-engine/scenarios/internal/attacksecurity/integeroverflow"
	"github.com/lenschain/sim-engine/scenarios/internal/attacksecurity/pbftbyzantine"
	"github.com/lenschain/sim-engine/scenarios/internal/attacksecurity/reentrancyattack"
	"github.com/lenschain/sim-engine/scenarios/internal/attacksecurity/selfishmining"
	"github.com/lenschain/sim-engine/scenarios/internal/framework"
)

// attackSecurityDefinitions 返回攻击与安全领域的 6 个场景定义。
func attackSecurityDefinitions() []framework.Definition {
	return []framework.Definition{
		buildDefinition(SceneTemplate{
			Code:            "51-percent-attack",
			Name:            "51% 算力攻击",
			Description:     "展示诚实链与攻击链竞赛和链重组。",
			CategoryCode:    "attack_security",
			AlgorithmType:   "51-percent-attack",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pow-attack-group"},
			Profile:         StepProfile{Stages: []string{"私链积累", "追平主链", "公开重组"}, TotalTicks: 18, StepDuration: 1500},
			BaseNodeLabels:  []string{"Honest-1", "Honest-2", "Attacker"},
			BaseNodeRole:    "miner",
			Actions:         []ActionSpec{{ActionCode: "boost_attacker_hashrate", Label: "提升攻击算力", Description: "提高攻击者算力占比。", Trigger: "form_submit", FieldKey: "ratio", FieldLabel: "算力比例", FieldType: "range", DefaultValue: "0.55"}},
			DefaultState:    fiftyoneattack.DefaultState,
			InitHandler:     fiftyoneattack.Init,
			StepHandler:     fiftyoneattack.Step,
			ActionHandler:   fiftyoneattack.HandleAction,
			SyncHandler:     fiftyoneattack.SyncSharedState,
			RenderBuilder:   fiftyoneattack.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "double-spend",
			Name:            "双花攻击",
			Description:     "展示冲突交易、确认数竞赛和商家风险。",
			CategoryCode:    "attack_security",
			AlgorithmType:   "double-spend",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			Profile:         StepProfile{Stages: []string{"发送商家交易", "秘密构造冲突交易", "替换已确认交易"}, TotalTicks: 16, StepDuration: 1400},
			BaseNodeLabels:  []string{"Merchant", "Attacker", "Miner"},
			BaseNodeRole:    "attack",
			Actions:         []ActionSpec{{ActionCode: "send_conflict_tx", Label: "发送冲突交易", Description: "构造一笔新的冲突交易。", Trigger: "click", FieldKey: "tx", FieldLabel: "交易标识", FieldType: "string", DefaultValue: "conflict-tx"}},
			DefaultState:    doublespend.DefaultState,
			InitHandler:     doublespend.Init,
			StepHandler:     doublespend.Step,
			ActionHandler:   doublespend.HandleAction,
			RenderBuilder:   doublespend.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "pbft-byzantine",
			Name:            "PBFT 拜占庭攻击",
			Description:     "展示异常副本、消息偏差和容错阈值变化。",
			CategoryCode:    "attack_security",
			AlgorithmType:   "pbft-byzantine",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pbft-attack-group"},
			Profile:         StepProfile{Stages: []string{"恶意消息注入", "投票偏差", "触发视图切换"}, TotalTicks: 18, StepDuration: 1500},
			BaseNodeLabels:  []string{"Replica-0", "Replica-1", "Replica-2", "Replica-3"},
			BaseNodeRole:    "replica",
			Actions:         []ActionSpec{{ActionCode: "forge_vote", Label: "伪造投票", Description: "让目标副本发送异常投票。", Trigger: "form_submit", FieldKey: "resource_id", FieldLabel: "副本标识", FieldType: "node_ref", DefaultValue: "Replica-2"}},
			DefaultState:    pbftbyzantine.DefaultState,
			InitHandler:     pbftbyzantine.Init,
			StepHandler:     pbftbyzantine.Step,
			ActionHandler:   pbftbyzantine.HandleAction,
			SyncHandler:     pbftbyzantine.SyncSharedState,
			RenderBuilder:   pbftbyzantine.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "reentrancy-attack",
			Name:            "重入攻击",
			Description:     "展示递归调用栈和余额被盗过程。",
			CategoryCode:    "attack_security",
			AlgorithmType:   "reentrancy-attack",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"contract-security-group"},
			Profile:         StepProfile{Stages: []string{"调用 withdraw", "回调重入", "余额清空", "修复对比"}, TotalTicks: 18, StepDuration: 1500},
			BaseNodeLabels:  []string{"Vault", "Attacker", "Fallback", "Balance"},
			BaseNodeRole:    "contract",
			Actions:         []ActionSpec{{ActionCode: "trigger_reentrancy", Label: "触发重入", Description: "让攻击合约再次进入 withdraw。", Trigger: "click", FieldKey: "depth", FieldLabel: "重入深度", FieldType: "number", DefaultValue: "2"}},
			DefaultState:    reentrancyattack.DefaultState,
			InitHandler:     reentrancyattack.Init,
			StepHandler:     reentrancyattack.Step,
			ActionHandler:   reentrancyattack.HandleAction,
			SyncHandler:     reentrancyattack.SyncSharedState,
			RenderBuilder:   reentrancyattack.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "integer-overflow",
			Name:            "整数溢出攻击",
			Description:     "展示数值回绕、临界点和 SafeMath 对比。",
			CategoryCode:    "attack_security",
			AlgorithmType:   "integer-overflow",
			Version:         "v1.0.0",
			TimeControlMode: "reactive",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"contract-security-group"},
			Profile:         StepProfile{Stages: []string{"逼近上限", "发生回绕", "保护拦截"}, TotalTicks: 10, StepDuration: 900},
			BaseNodeLabels:  []string{"Before", "Critical", "After"},
			BaseNodeRole:    "value",
			Actions:         []ActionSpec{{ActionCode: "add_value", Label: "增加数值", Description: "对目标值执行加法运算。", Trigger: "form_submit", FieldKey: "delta", FieldLabel: "增量", FieldType: "number", DefaultValue: "1"}},
			DefaultState:    integeroverflow.DefaultState,
			InitHandler:     integeroverflow.Init,
			StepHandler:     integeroverflow.Step,
			ActionHandler:   integeroverflow.HandleAction,
			SyncHandler:     integeroverflow.SyncSharedState,
			RenderBuilder:   integeroverflow.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "selfish-mining",
			Name:            "自私挖矿",
			Description:     "展示私有链积累、公开策略和收益对比。",
			CategoryCode:    "attack_security",
			AlgorithmType:   "selfish-mining",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			Profile:         StepProfile{Stages: []string{"私链积累", "条件公开", "收益比较"}, TotalTicks: 16, StepDuration: 1400},
			BaseNodeLabels:  []string{"Honest", "Selfish", "Public"},
			BaseNodeRole:    "miner",
			Actions:         []ActionSpec{{ActionCode: "publish_private_chain", Label: "公开私链", Description: "公开已累积的私有区块链。", Trigger: "click", FieldKey: "blocks", FieldLabel: "区块数量", FieldType: "number", DefaultValue: "2"}},
			DefaultState:    selfishmining.DefaultState,
			InitHandler:     selfishmining.Init,
			StepHandler:     selfishmining.Step,
			ActionHandler:   selfishmining.HandleAction,
			RenderBuilder:   selfishmining.BuildRenderState,
		}),
	}
}
