package catalog

import (
	"github.com/lenschain/sim-engine/scenarios/internal/economic/defiliquidity"
	"github.com/lenschain/sim-engine/scenarios/internal/economic/gasmarket"
	"github.com/lenschain/sim-engine/scenarios/internal/economic/governancevoting"
	"github.com/lenschain/sim-engine/scenarios/internal/economic/posstaking"
	"github.com/lenschain/sim-engine/scenarios/internal/economic/tokeneconomics"
	"github.com/lenschain/sim-engine/scenarios/internal/framework"
)

// economicDefinitions 返回经济模型领域的 5 个场景定义。
func economicDefinitions() []framework.Definition {
	return []framework.Definition{
		buildDefinition(SceneTemplate{
			Code:            "token-economics",
			Name:            "Token 经济模型",
			Description:     "展示供应量曲线、分配比例和释放节奏。",
			CategoryCode:    "economic",
			AlgorithmType:   "token-economics",
			Version:         "v1.0.0",
			TimeControlMode: "reactive",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pos-economy-group"},
			Profile:         StepProfile{Stages: []string{"初始分配", "线性释放", "通胀调整", "供应观察"}, TotalTicks: 16, StepDuration: 1200},
			BaseNodeLabels:  []string{"Team", "Treasury", "Community", "Validators"},
			BaseNodeRole:    "holder",
			Actions:         []ActionSpec{{ActionCode: "switch_release_model", Label: "切换释放模型", Description: "调整通胀率与释放节奏。", Trigger: "form_submit", FieldKey: "inflation_rate", FieldLabel: "年化通胀率", FieldType: "number", DefaultValue: "0.04"}},
			DefaultState:    tokeneconomics.DefaultState,
			InitHandler:     tokeneconomics.Init,
			StepHandler:     tokeneconomics.Step,
			ActionHandler:   tokeneconomics.HandleAction,
			SyncHandler:     tokeneconomics.SyncSharedState,
			RenderBuilder:   tokeneconomics.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "pos-staking",
			Name:            "PoS 质押经济",
			Description:     "展示质押量、收益率和 Slash 事件。",
			CategoryCode:    "economic",
			AlgorithmType:   "pos-staking",
			Version:         "v1.0.0",
			TimeControlMode: "continuous",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pos-economy-group"},
			Profile:         StepProfile{Stages: []string{"汇总质押", "分发奖励", "罚没 Slash"}, TotalTicks: 16, StepDuration: 1200},
			BaseNodeLabels:  []string{"Validator-A", "Validator-B", "Validator-C", "Delegator"},
			BaseNodeRole:    "staking",
			Actions:         []ActionSpec{{ActionCode: "apply_slash", Label: "执行 Slash", Description: "对目标验证者施加罚没。", Trigger: "click", FieldKey: "resource_id", FieldLabel: "验证者标识", FieldType: "node_ref", DefaultValue: "Validator-A"}},
			DefaultState:    posstaking.DefaultState,
			InitHandler:     posstaking.Init,
			StepHandler:     posstaking.Step,
			ActionHandler:   posstaking.HandleAction,
			SyncHandler:     posstaking.SyncSharedState,
			RenderBuilder:   posstaking.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "governance-voting",
			Name:            "链上治理投票",
			Description:     "展示提案生命周期、投票权重和法定人数。",
			CategoryCode:    "economic",
			AlgorithmType:   "governance-voting",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pos-economy-group"},
			Profile:         StepProfile{Stages: []string{"提出提案", "投票期", "达到法定人数", "执行提案"}, TotalTicks: 18, StepDuration: 1400},
			BaseNodeLabels:  []string{"Proposal", "Voter-A", "Voter-B", "Executor"},
			BaseNodeRole:    "governance",
			Actions:         []ActionSpec{{ActionCode: "cast_vote", Label: "投票", Description: "向提案投票。", Trigger: "form_submit", FieldKey: "choice", FieldLabel: "投票选项", FieldType: "string", DefaultValue: "yes"}},
			DefaultState:    governancevoting.DefaultState,
			InitHandler:     governancevoting.Init,
			StepHandler:     governancevoting.Step,
			ActionHandler:   governancevoting.HandleAction,
			SyncHandler:     governancevoting.SyncSharedState,
			RenderBuilder:   governancevoting.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "defi-liquidity",
			Name:            "DeFi 流动性池",
			Description:     "展示 AMM 曲线、滑点和无常损失。",
			CategoryCode:    "economic",
			AlgorithmType:   "defi-liquidity",
			Version:         "v1.0.0",
			TimeControlMode: "reactive",
			DataSourceMode:  "simulation",
			Profile:         StepProfile{Stages: []string{"池子初始化", "交易撮合", "价格偏移", "无常损失"}, TotalTicks: 12, StepDuration: 900},
			BaseNodeLabels:  []string{"Pool-X", "Pool-Y", "LP", "Trader"},
			BaseNodeRole:    "amm",
			Actions:         []ActionSpec{{ActionCode: "swap_asset", Label: "执行兑换", Description: "执行一次资产兑换。", Trigger: "form_submit", FieldKey: "amount", FieldLabel: "兑换数量", FieldType: "number", DefaultValue: "20"}},
			DefaultState:    defiliquidity.DefaultState,
			InitHandler:     defiliquidity.Init,
			StepHandler:     defiliquidity.Step,
			ActionHandler:   defiliquidity.HandleAction,
			RenderBuilder:   defiliquidity.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "gas-market",
			Name:            "Gas 费市场（EIP-1559）",
			Description:     "展示基础费、区块利用率和燃烧量变化。",
			CategoryCode:    "economic",
			AlgorithmType:   "gas-market",
			Version:         "v1.0.0",
			TimeControlMode: "continuous",
			DataSourceMode:  "simulation",
			Profile:         StepProfile{Stages: []string{"采样利用率", "调整基础费", "统计燃烧"}, TotalTicks: 16, StepDuration: 1200},
			BaseNodeLabels:  []string{"BaseFee", "Tip", "Burn", "BlockUtilization"},
			BaseNodeRole:    "fee",
			Actions:         []ActionSpec{{ActionCode: "spike_demand", Label: "提升需求", Description: "模拟短期交易需求激增。", Trigger: "click", FieldKey: "demand", FieldLabel: "需求倍率", FieldType: "number", DefaultValue: "2"}},
			DefaultState:    gasmarket.DefaultState,
			InitHandler:     gasmarket.Init,
			StepHandler:     gasmarket.Step,
			ActionHandler:   gasmarket.HandleAction,
			RenderBuilder:   gasmarket.BuildRenderState,
		}),
	}
}
