package catalog

import (
	"github.com/lenschain/sim-engine/scenarios/internal/framework"
	"github.com/lenschain/sim-engine/scenarios/internal/nodenetwork/blocksync"
	"github.com/lenschain/sim-engine/scenarios/internal/nodenetwork/gossippropagation"
	"github.com/lenschain/sim-engine/scenarios/internal/nodenetwork/networkpartition"
	"github.com/lenschain/sim-engine/scenarios/internal/nodenetwork/nodeloadbalance"
	"github.com/lenschain/sim-engine/scenarios/internal/nodenetwork/p2pdiscovery"
	"github.com/lenschain/sim-engine/scenarios/internal/nodenetwork/txbroadcast"
)

// nodeNetworkDefinitions 返回节点与网络领域的 6 个场景定义。
func nodeNetworkDefinitions() []framework.Definition {
	return []framework.Definition{
		buildDefinition(SceneTemplate{
			Code:            "p2p-discovery",
			Name:            "P2P 网络发现与路由",
			Description:     "展示节点发现、邻居路由表收敛和拓扑稳定过程。",
			CategoryCode:    "node_network",
			AlgorithmType:   "p2p-discovery",
			Version:         "v1.0.0",
			TimeControlMode: "continuous",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"network-base-group"},
			Profile:         StepProfile{Stages: []string{"节点发现", "邻居交换", "路由收敛"}, TotalTicks: 18, StepDuration: 1400},
			BaseNodeLabels:  []string{"Peer-A", "Peer-B", "Peer-C", "Peer-D", "Peer-E"},
			BaseNodeRole:    "peer",
			Actions: []ActionSpec{
				{ActionCode: "add_peer", Label: "新增节点", Description: "向网络中加入一个新节点。", Trigger: "form_submit", FieldKey: "peer_label", FieldLabel: "节点名称", FieldType: "string", DefaultValue: "Peer-X"},
				{ActionCode: "shuffle_route", Label: "扰动路由", Description: "模拟节点路由表刷新。", Trigger: "click", FieldKey: "resource_id", FieldLabel: "目标节点", FieldType: "node_ref", DefaultValue: "Peer-A"},
			},
			DefaultState:  p2pdiscovery.DefaultState,
			InitHandler:   p2pdiscovery.Init,
			StepHandler:   p2pdiscovery.Step,
			ActionHandler: p2pdiscovery.HandleAction,
			SyncHandler:   p2pdiscovery.SyncSharedState,
			RenderBuilder: p2pdiscovery.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "gossip-propagation",
			Name:            "Gossip 消息传播",
			Description:     "展示消息从源节点向全网扩散的覆盖过程。",
			CategoryCode:    "node_network",
			AlgorithmType:   "gossip-propagation",
			Version:         "v1.0.0",
			TimeControlMode: "continuous",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"network-base-group"},
			Profile:         StepProfile{Stages: []string{"源节点广播", "邻居转发", "全网覆盖"}, TotalTicks: 15, StepDuration: 1200},
			BaseNodeLabels:  []string{"Seed", "Relay-1", "Relay-2", "Relay-3", "Relay-4"},
			BaseNodeRole:    "relay",
			Actions: []ActionSpec{
				{ActionCode: "seed_message", Label: "投放消息", Description: "从源节点注入新的消息。", Trigger: "form_submit", FieldKey: "message_label", FieldLabel: "消息标签", FieldType: "string", DefaultValue: "TX-001"},
			},
			DefaultState:  gossippropagation.DefaultState,
			InitHandler:   gossippropagation.Init,
			StepHandler:   gossippropagation.Step,
			ActionHandler: gossippropagation.HandleAction,
			SyncHandler:   gossippropagation.SyncSharedState,
			RenderBuilder: gossippropagation.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "network-partition",
			Name:            "网络分区与恢复",
			Description:     "展示网络隔离边界形成和恢复同步流程。",
			CategoryCode:    "node_network",
			AlgorithmType:   "network-partition",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pbft-attack-group", "raft-fault-group"},
			Profile:         StepProfile{Stages: []string{"正常通信", "形成分区", "隔离维持", "恢复同步"}, TotalTicks: 20, StepDuration: 1600},
			BaseNodeLabels:  []string{"Zone-A1", "Zone-A2", "Zone-B1", "Zone-B2"},
			BaseNodeRole:    "router",
			Actions: []ActionSpec{
				{ActionCode: "cut_link", Label: "切断链路", Description: "人为制造分区边界。", Trigger: "click", FieldKey: "resource_id", FieldLabel: "目标链路", FieldType: "string", DefaultValue: "A-B"},
				{ActionCode: "restore_link", Label: "恢复链路", Description: "恢复隔离网络间的链路。", Trigger: "click", FieldKey: "resource_id", FieldLabel: "目标链路", FieldType: "string", DefaultValue: "A-B"},
			},
			DefaultState:  networkpartition.DefaultState,
			InitHandler:   networkpartition.Init,
			StepHandler:   networkpartition.Step,
			ActionHandler: networkpartition.HandleAction,
			SyncHandler:   networkpartition.SyncSharedState,
			RenderBuilder: networkpartition.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "tx-broadcast",
			Name:            "交易广播与打包",
			Description:     "展示交易广播、矿工收集和内存池填充。",
			CategoryCode:    "node_network",
			AlgorithmType:   "tx-broadcast",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			Profile:         StepProfile{Stages: []string{"创建交易", "网络广播", "内存池堆积", "矿工收集"}, TotalTicks: 16, StepDuration: 1400},
			BaseNodeLabels:  []string{"Wallet", "Peer-1", "Peer-2", "Miner"},
			BaseNodeRole:    "node",
			Actions: []ActionSpec{
				{ActionCode: "broadcast_tx", Label: "发起交易", Description: "广播一笔新的交易。", Trigger: "form_submit", FieldKey: "tx_label", FieldLabel: "交易标识", FieldType: "string", DefaultValue: "tx-1001"},
			},
			DefaultState:  txbroadcast.DefaultState,
			InitHandler:   txbroadcast.Init,
			StepHandler:   txbroadcast.Step,
			ActionHandler: txbroadcast.HandleAction,
			RenderBuilder: txbroadcast.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "block-sync",
			Name:            "区块同步与传播",
			Description:     "展示新区块传播、高度追平和分叉检测。",
			CategoryCode:    "node_network",
			AlgorithmType:   "block-sync",
			Version:         "v1.0.0",
			TimeControlMode: "process",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"pow-attack-group", "raft-fault-group"},
			Profile:         StepProfile{Stages: []string{"出块", "广播", "高度追平", "分叉检测"}, TotalTicks: 20, StepDuration: 1500},
			BaseNodeLabels:  []string{"Producer", "Follower-1", "Follower-2", "Follower-3"},
			BaseNodeRole:    "validator",
			Actions: []ActionSpec{
				{ActionCode: "inject_block", Label: "注入新区块", Description: "向网络注入新区块以触发同步。", Trigger: "click", FieldKey: "block_height", FieldLabel: "区块高度", FieldType: "number", DefaultValue: "10"},
			},
			DefaultState:  blocksync.DefaultState,
			InitHandler:   blocksync.Init,
			StepHandler:   blocksync.Step,
			ActionHandler: blocksync.HandleAction,
			SyncHandler:   blocksync.SyncSharedState,
			RenderBuilder: blocksync.BuildRenderState,
		}),
		buildDefinition(SceneTemplate{
			Code:            "node-load-balance",
			Name:            "节点负载均衡",
			Description:     "展示网络请求在节点间的路由与迁移。",
			CategoryCode:    "node_network",
			AlgorithmType:   "node-load-balance",
			Version:         "v1.0.0",
			TimeControlMode: "continuous",
			DataSourceMode:  "simulation",
			LinkGroups:      []string{"network-base-group"},
			Profile:         StepProfile{Stages: []string{"采集负载", "评估热点", "迁移流量"}, TotalTicks: 14, StepDuration: 1200},
			BaseNodeLabels:  []string{"LB-1", "LB-2", "LB-3", "LB-4"},
			BaseNodeRole:    "gateway",
			Actions: []ActionSpec{
				{ActionCode: "shift_traffic", Label: "迁移流量", Description: "将流量迁移到其他节点。", Trigger: "drag", FieldKey: "resource_id", FieldLabel: "目标节点", FieldType: "node_ref", DefaultValue: "LB-2"},
			},
			DefaultState:  nodeloadbalance.DefaultState,
			InitHandler:   nodeloadbalance.Init,
			StepHandler:   nodeloadbalance.Step,
			ActionHandler: nodeloadbalance.HandleAction,
			SyncHandler:   nodeloadbalance.SyncSharedState,
			RenderBuilder: nodeloadbalance.BuildRenderState,
		}),
	}
}
