apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sim-engine
  namespace: lenschain-platform
  labels:
    app.kubernetes.io/name: sim-engine
    app.kubernetes.io/part-of: lenschain
spec:
  rules:
    - host: sim-engine-dev.lenschain.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sim-engine
                port:
                  number: 8090
